services:
  bluebeep-api:
    build: .
    container_name: bluebeep
    restart: always
    env_file:
      - .env
    ports:
      - '4001:4001'
    depends_on:
      - redis
    networks:
      - bluebeep-network
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - bluebeep-network
    env_file:
      - .env
#    volumes:
#      - ./redis/data:/data
#    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
networks:
  bluebeep-network:
    driver: bridge
